### PR TITLE
Feat/network synced registries

### PR DESCRIPTION
**Pull request by libraryaddict**
This does break the existing "JukeboxSong" implementation, notably the constructor. Not sure if anyone was using that.

### CODE REVIEW

**Comment by libraryaddict** [comment]
Draft because I didn't test this beyond the basics of "Yep, I can join the server".
This only addresses the two missing registries, did add a changed biome registry change. But didn't verify if more than that changed.
Not sure how you're testing this.

Didn't @ you on discord because I didn't feel chatty today sorry

**Comment by booky10** [comment]
First of all, thanks for the PR! I've only skimmed it for now, I'll take a closer look at it later. 

You've changed the JukeboxSong class to an interface, so this is currently a breaking change for all uses of it - wouldn't it make more sense to deprecate the old class instead and add a new interface with a different name?

**Comment by libraryaddict** [comment]
Personally I would've gone ahead as a breaking change as it's 1.5 months old, but unfortunately it was in the last release.

I've changed it to a class again, and the interface is instead called "JukeboxSongInterface"
Which is a bit of a mouthful but eh.

**Comment by booky10** [comment]
what do you think of `IJukeboxSong`?

**Comment by Bram1903** [comment]
> what do you think of `IJukeboxSong`?

Personally I really like using "I" as interface naming convention. This is common practice in C# as well and makes it much easier to understand what a certain file is for. Especially when looking at it from outside an IDE.

**Review by booky10 — APPROVED** [review]

**Comment by booky10** [comment]
Made some changes to fix a small backwards compatibility issue and some minor inconsistencies
Thanks for the PR, it helped a lot :+1:

**Pull request merged**
